two_M_field_lengths:
    tax_ext_parcel_book_map_item: 8
    item_split: 1
    tax_ext_rec_seq_num: 2
    tax_ext_rec_type: 2
    area_code: 6
    assr_exempt_code: 1
    bt_cp_code: 1
    mtg_code: 4
    loan_num_1_8: 8
    primary_land_assessed_value: 12
    primary_improve_assessed_value: 12
    res_phase_num: 4
    filler_1: 4
    wid_vet_exempt_amt: 12
    primary_net_assessed_value: 12
    state_tax: 10
    county_tax: 10
    jr_college_tax: 10
    school_tax: 10
    city_tax: 10
    tot_primary_half_tax: 10
    flood_tax: 10
    cawcd_tax: 10
    bond_tax: 10
    other_tax: 10
    fire_dist_tax: 10
    library_tax: 10
    health_tax: 10
    elem_sec_tax: 10
    hs_sec_tax: 10
    tot_sec_half_tax: 10
    loan_num_9_12: 4
    primary_land_assessed_class: 2
    primary_land_assessed_ratio: 3
    primary_land_full_cash_value: 12
    primary_improve_assessed_class: 2
    primary_improve_assessed_ratio: 3
    primary_improve_full_cash_value: 12
    state_rate: 6
    county_rate: 6
    school_rate: 6
    jr_college_rate: 6
    city_rate: 6
    area_code_tax_rate: 7
    flood_rate: 6
    cawcd_rate: 6
    bond_rate: 6
    other_rate: 6
    fire_dist_rate: 6
    library_rate: 6
    health_rate: 6
    elem_sec_rate: 6
    hs_sec_rate: 6
    sec_land_assessed_value: 12
    sec_improve_assessed_value: 12
    sec_wid_vet_exempt_amt: 12
    sec_net_assessed_value: 12
    sec_land_full_cash_value: 12
    sec_improve_full_cash_value: 12
    sec_land_ratio: 3
    sec_improve_ratio: 3
    residen_pct: 4
    elem_state_aid_amt: 10
    hs_state_aid_amt: 9
    addnl_elem_state_aid_amt: 9
    addnl_hs_state_aid_amt: 9
    res_num: 5
    res_reason: 2
    res_disapproval: 2
    res_phase_num_old: 2
    res_split: 3
    bill_print_blank: 1
    bank_key: 4
    elem_eaf: 9
    hs_eaf: 9
    filler_2: 10

two_P_field_lengths:
  tax_ext_parcel_book_map_item: 8
  item_split: 1
  tax_ext_rec_seq_num: 2
  tax_ext_rec_type: 2
  area_code: 6
  assr_exempt_code: 1
  filler_0: 33
  primary_assessed_value: 12
  primary_wid_vet_exempt_amt: 12
  primary_net_assessed_value: 12
  state_tax: 10
  county_tax: 10
  jr_college_tax: 10
  school_tax: 10
  city_tax: 10
  tot_primary_half_tax_amt: 10
  filler_1: 10
  cawcd_tax: 10
  bond_tax: 10
  other_tax: 10
  fire_dist_tax: 10
  library_tax: 10
  health_tax: 10
  elem_sec_tax: 10
  hs_sec_tax: 10
  tot_secondary_half_tax_amt: 10
  filler_2: 21
  primary_assessed_class: 2
  primary_assessed_ratio: 3
  primary_full_cash_value: 12
  state_rate: 6
  county_rate: 6
  school_rate: 6
  jr_college_rate: 6
  city_rate: 6
  area_code_tax_rate: 7
  filler_3: 6
  cawcd_rate: 6
  bond_rate: 6
  other_rate: 6
  fire_dist_rate: 6
  library_rate: 6
  health_rate: 6
  elem_sec_rate: 6
  hs_sec_rate: 6
  filler_4: 12
  assessed_value: 12
  wid_vet_exempt_amt: 12
  net_assessed_value: 12
  filler_5: 12
  assessed_full_cash_value: 12
  elem_state_aid_amt: 10
  addnl_elem_state_aid_amt: 10
  hs_state_aid_amt: 10
  addnl_hs_state_aid_amt: 10
  filler_6: 5
  res_num: 5
  res_reason: 2
  res_disapproval: 2
  res_phase_num_old: 2
  res_phase_num: 4
  filler_7: 4
  elem_eaf: 9
  hs_eaf: 9
  filler_8: 10

two_S_field_lengths:
  tax_ext_parcel_book_map_item: 8
  item_split: 1
  tax_ext_rec_seq_num: 2
  tax_ext_rec_type: 2
  area_code: 6
  assr_exempt_code: 1
  filler_1: 13
  assessed_value: 12
  assr_value_type: 1
  filler_2: 23
  net_assessed_value: 12
  filler_3: 40
  spec_dist_tax: 10
  spec_dist_half_tax: 10
  spec_dist_state_aid: 10
  fund_x_eaf: 9
  filler_4: 111
  spec_dist_tax_rate: 8
  filler_5: 184
  res_num: 5
  res_reason: 2
  res_disapproval: 2
  res_phase_num_old: 2
  res_phase_num: 4
  filler_6: 4
  filler_7: 60